### PR TITLE
Add more missing vocab items

### PR DESCRIPTION
**Pull request by randy5235**
In reference to Issue https://github.com/dahlia/fedify/issues/65

Add:
vocab/arrive.yaml
vocab/invite.yaml
vocab/join.yaml
vocab/leave.yaml
vocab/listen.yaml

Updated the snapshot per the contribution instructions.
I did have to update the snapshots as they were missing some references to the new vocab items

Please verify the snapshots look correct, I would rather not introduce a bad snapshot.

Please reach out if there is anything further I can add to help this land.

### CODE REVIEW

**Review by dahlia — COMMENTED** [review]
Thank you very much for your contributions!  Could you add relevant entries to the changelog (*CHANGES.md*) and *FEDERATION.md*?

**Comment by randy5235** [comment]
Absolutely.

**Review by dahlia — CHANGES_REQUESTED** [review]
Oops, all the Markdown files have been reformatted, could you please just add the content without the formatting changes?

**Comment by randy5235** [comment]
> Oops, all the Markdown files have been reformatted, could you please just add the content without the formatting changes?

Sorry about that, my local lint rules reformatted it. It should be fixed now.

**Review by dahlia — APPROVED** [review]
Everything looks fine, I'm going to merge this soon!

**Pull request merged**
