### PR TITLE
Add `Offer` class to Activity Vocabulary API

### PR DESCRIPTION
**Pull request by moreal**
It resolves a part of #65. It adds `Offer` class to Activity Vocabulary API.

### CODE REVIEW

**Review by dahlia — COMMENTED** [review]
You should update snapshots for snapshot tests.  It can be updated by running `deno task test -- --update`.

**Comment by moreal** [comment]
@dahlia Thank you! I updated the snapshots and I'll mark as ready-for-review after the checks passed.

**Comment by moreal** [comment]
The `publish-docs` check is failing. It may have an error when using `nwtgck/actions-netlify@v3.0` action 🤔 (I cannot see logs). Because #68 is merged though the task was failed in the PR too, I mark this pull request as ready-for-review.

**Comment by dahlia** [comment]
> The `publish-docs` check is failing. It may have an error when using `nwtgck/actions-netlify@v3.0` action 🤔 (I cannot see logs). Because #68 is merged though the task was failed in the PR too, I mark this pull request as ready-for-review.

That's my fault; I have to fix the CI. Never mind!

**Review by dahlia — APPROVED** [review]

**Pull request merged**
